packages:
  - benches/*

overrides:
  "@eslint/markdown": "-"
  "@stylistic/eslint-plugin": "-"
  eslint-plugin-jsonc: "-"
  eslint-plugin-toml: "-"
  eslint-plugin-vue: "-"
  eslint-processor-vue-blocks: "-"
  eslint-plugin-yml: "-"
  jsonc-eslint-parser: "-"
  toml-eslint-parser: "-"
  yaml-eslint-parser: "-"
  indent-string: npm:@socketregistry/indent-string@^1
  is-core-module: npm:@socketregistry/is-core-module@^1
  object-assign: npm:@socketregistry/object-assign@^1
  path-parse: npm:@socketregistry/path-parse@^1

savePrefix: ""
shellEmulator: true
minimumReleaseAge: 2880
