packages:
  - benches/*

allowBuilds:
  simple-git-hooks: false

dedupePeers: true
dedupePeerDependents: true

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - alleviate@0.0.0-alpha.2
  # Renovate security update: js-yaml@5.4.1
  - js-yaml@5.4.1

overrides:
  indent-string: npm:@socketregistry/indent-string@^1
  is-core-module: npm:@socketregistry/is-core-module@^1
  jsonc-eslint-parser: "-"
  object-assign: npm:@socketregistry/object-assign@^1
  path-parse: npm:@socketregistry/path-parse@^1
  toml-eslint-parser: "-"
  yaml-eslint-parser: "-"

savePrefix: ""
shellEmulator: true
